CREATE TABLE IF NOT EXISTS projects (
        id integer PRIMARY KEY GENERATED BY
            DEFAULT AS IDENTITY,
            name text NOT NULL CHECK (name <> ''),
            priority integer NOT NULL,
            description text,
            deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
        id integer PRIMARY KEY GENERATED BY
            DEFAULT AS IDENTITY,
            name text NOT NULL,
            done boolean,
            projectId integer REFERENCES projects (id)
);

INSERT INTO projects (name, priority, description, deliverydate)
        VALUES ('Learning PG', 2, 'https://www.youtube.com/watch?v=sA3t4d1v7OI', TO_DATE('04/06/2019', 'DD/MM/YYYY'));

INSERT INTO tasks(name,done,projectId)
VALUES ('Create WIREFRAME','f',2);


npx sequelize-cli model:generate --name tasks --attributes id:integer,name:string,status:boolean,description:string,project_id:integer


npx sequelize-cli model:generate --name projects --attributes id:integer,name:string,priority:integer,description:string


